version: "3.7"
services:
    app:
        build:
            args:
                user: test
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: api-blog
        container_name: api-blog
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - api-blog

    db:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3307:3306
        networks:
            - api-blog

    nginx:
        image: nginx:1.17-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - api-blog

    phpmyadmin:
        image: phpmyadmin
        restart: always
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - 8080:80
        networks:
            - api-blog

networks:
    api-blog:
        driver: bridge
